
["Cute Hermit Crabs"]
	#Hermit Crab Shell Resistance Level
	#Range: 1 ~ 3
	"Resistance Level" = 3
	#Hermit Crab Spawn Weight
	"Spawn Weight" = 10
	#Hermit Crab Min Group Size
	"Min Group Size" = 2
	#Hermit Crab Max Group Size
	"Max Group Size" = 6

