
#Dramatic Doors
[Mixins]
	#Allow doors to be waterlogged. Enable to allow waterlogging. Disable for compatibility with certain mods. Requires restart after changing.  Default: true
	waterloggable_doors = false
	#Allow fence gates to be waterlogged. Enable to allow waterlogging. Disable for compatibility with certain mods. Requires restart after changing.  Default: true
	waterloggable_fence_gates = false

