
["Config for Enchantment Transfer!"]
	#Here you can set a fixed value for any enchantment transfer from item to book. Default is 1000 which disables the fixed value.
	"Fixed Experience Cost" = 1000
	#Here you can set a factor to multiply any enchantment transfer XP cost by. This will be overwritten if a fixed value other than 1000 is defined. Default is 1.0.
	"Experience Cost Factor" = 1.0
	#Here you can set an enchantment limit to only transfer X amount of enchantments from an item. Default is 1000 which disables the limit.
	"Enchantment Limit" = 1000

