
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Allows the mod to try to remap and convert other blocks and items from other compat mods that have been uninstalled from one world. This was made so one can uninstall such mods seamlessly having their blocks converted into Evety Compat counterparts
	remap_other_mods = false
	#Clears out and remaps all blocks registered by this mod belonging to uninstalled wood types to air or oak wood
	remap_self = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true

[wood_type]

	[wood_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		crimson = true
		warped = true

	[wood_type.twigs]
		bamboo = true

	[wood_type.ecologics]
		flowering_azalea = true
		coconut = true
		walnut = true
		azalea = true

	[wood_type.nethers_exoticism]
		ramboutan = true

	[wood_type.thewildupdate]
		mangrove = true

	[wood_type.pizzacraft]
		olive = true

	[wood_type.tropicraft]
		mahogany = true
		palm = true

	[wood_type.architects_palette]
		twisted = true

	[wood_type.biomemakeover]
		blighted_balsa = true
		willow = true
		swamp_cypress = true
		ancient_oak = true

	[wood_type.orcz]
		orc_wood = true

	[wood_type.quark]
		blossom = true
		azalea = true

	[wood_type.valhelsia_structures]
		lapidified_jungle = true

	[wood_type.forbidden_arcanus]
		fungyss = true
		cherrywood = true
		mysterywood = true
		edelwood = true

[leaves_type]

	[leaves_type.minecraft]
		oak = true
		spruce = true
		birch = true
		jungle = true
		acacia = true
		dark_oak = true
		azalea = true
		flowering_azalea = true

	[leaves_type.twigs]
		bamboo = true

	[leaves_type.nethers_exoticism]
		ramboutan = true
		jaboticaba = true

	[leaves_type.thewildupdate]
		mangrove = true

	[leaves_type.ecologics]
		coconut = true
		walnut = true

	[leaves_type.pizzacraft]
		olive = true
		fruit_olive = true

	[leaves_type.tropicraft]
		mahogany = true
		palm = true
		kapok = true
		fruit = true
		grapefruit = true
		lemon = true
		lime = true
		orange = true
		papaya = true
		red_mangrove = true
		tall_mangrove = true
		tea_mangrove = true
		black_mangrove = true

	[leaves_type.architects_palette]
		twisted = true

	[leaves_type.biomemakeover]
		blighted_balsa = true
		willow = true
		swamp_cypress = true
		ancient_oak = true

	[leaves_type.orcz]
		orc_wood = true

	[leaves_type.quark]
		blue_blossom = true
		lavender_blossom = true
		orange_blossom = true
		pink_blossom = true
		yellow_blossom = true
		red_blossom = true

	[leaves_type.culturaldelights]
		avocado = true

	[leaves_type.ars_nouveau]
		blue_archwood = true
		red_archwood = true
		green_archwood = true
		purple_archwood = true

	[leaves_type.forbidden_arcanus]
		cherrywood = true
		mysterywood = true
		nuggety_mysterywood = true

