
[reskin]
	#list of entities (minecraft:cow, etc) that will have the capacity to be reskinned via NBT
	entity_list = ["minecraft:cow"]

[effects]
	#the size of the explosion caused by the explosive effect
	#Range: 0.0 ~ 1.7976931348623157E308
	explosion_size = 2.0
	#the type of explosion mode for blocks  options: NONE, BREAK, DESTROY. none does nothing, break breaks blocks, destroy breaks & destroys blocks.
	explosion_mode = "break"
	#the chance of being granted slowness x while under the effects of the drumble debuff, expressed as 1 in X
	#Range: > 0
	fumble_chance = 30
	#the maximum amount of durability damage applied (randomly from 1 to X)
	#Range: > 0
	durability_damage = 3
	#the chance as a percent per tick of the potion effect that a tool or sword will take durability damage
	#Range: 0.0 ~ 1.7976931348623157E308
	durability_chance = 0.015
	#whether or not crumble will damage items at or below 10 durability
	nice_mode = true
	#whether or not potion effects given by bees should persist through death
	effects_persist = true
	#the amount of knockback that should be added to an entity's attacks
	#Range: 0.0 ~ 5.0
	knockback = 5.0
	#the amount of knockup that should be added to an entity's attacks
	#Range: 0.0 ~ 5.0
	knockup = 1.8
	#whether or not potion effects should show particles
	hide_particles = false

[commands]
	#whether or not the potion id command should be registered [default: true]
	register_potion = true
	#whether commands should be registered for each time (/midnight, /night, /sunrise, etc) [default: true]
	register_time = true
	#the permission level required for all commands
	#Range: 0 ~ 4
	permission_level = 2

	[commands."time commands"]
		#the length of a day in ticks [default: 24,000]
		#Range: 0 ~ 9223372036854775807
		day_length = 24000
		#the value of 'night', i.e., when you can sleep in a bed [default: 12542]
		#Range: > 0
		night_time = 12010
		#the value of midnight [default: 18000]
		#Range: > 0
		midnight_time = 18000
		#the value of 'morning', i.e., when you wake up [default: 0
		#Range: > 0
		morning_time = 0
		#the value of sunset [default: 12000]
		#Range: > 0
		sunset_time = 12000
		#the value of sunrise [default: 23000]
		#Range: > 0
		dawn_time = 23000
		#the value of midday or noon [default: 6000]
		#Range: > 0
		midday_time = 6000

