
["PiggyBank Drop Settings"]
	#Range: 0 ~ 999999
	"Experience Points Dropped by the PiggyBank" = 100
	#Range: 1 ~ 300
	"Spawn Weight" = 5
	#Range: 1 ~ 300
	"Min Pigs to Spawn in Group" = 1
	#Range: 1 ~ 300
	"Max Pigs to Spawn in Group" = 1

