#Chance of the smoke particle to spawn. 1.0 - full. 0.0 - no smoke.
#Range: 0.0 ~ 1.0
SmokeChance = 1.0
#0.0 - chimney will never get dirty.
#Range: 0.0 ~ 1.0
DirtyChance = 0.05
#Enable/disable wind effect on smoke particles:
Wind = true

[JEI]
	#Soot Covering category will be added to JEI.
	#If 'DirtyChance' is set to 0 - it will not be added regardless of this setting
	JEISootCovering = true
	#Soot Scraping category will be added to JEI.
	JEISootScraping = true
	#Enables/disables 'May produce a byproduct' info in JEI Soot Scraping recipes.
	#Useful when scraping loot is removed.
	DisplayJEIScrapingByproductInfo = true

