#Chance of the smoke particle to spawn. 1.0 - full. 0.0 - no smoke.
#Range: 0.0 ~ 1.0
SmokeChance = 1.0
#0.0 - chimney will never get dirty.
#Range: 0.0 ~ 1.0
DirtyChance = 0.05
#Enable/disable wind effect on smoke particles:
Wind = true

