
[triggers]

	[triggers.sleep]
		#Whether the sleep curse trigger should be disabled.
		disabled = false

	[triggers.chop_tree]
		#Whether the chop_tree curse trigger should be disabled.
		disabled = false

	[triggers.dig_dirt]
		#Whether the dig_dirt curse trigger should be disabled.
		disabled = false

	[triggers.bone_meal]
		#Whether the bone_meal curse trigger should be disabled.
		disabled = false

	[triggers.mine_ore]
		#Whether the mine_ore curse trigger should be disabled.
		disabled = false

	[triggers.eat]
		#Whether the eat curse trigger should be disabled.
		disabled = false

	[triggers.kill_mob]
		#Whether the kill_mob curse trigger should be disabled.
		disabled = false

	[triggers.sneak]
		#Whether the sneak curse trigger should be disabled.
		disabled = false

	[triggers.mine_stone]
		#Whether the mine_stone curse trigger should be disabled.
		disabled = false

	[triggers.jump]
		#Whether the jump curse trigger should be disabled.
		disabled = false

[curses]

	[curses.explosion]
		#The chance of the explosion event being triggered. Set to 0 to disable.
		chance = 0.05000000074505806
		#The badness of the explosion curse event. Determines what doll tiers can cause it.
		#Allowed Values: BAD, WORSE, WORST
		badness = "WORST"
		#The set of tags for blocks that the explosion event should destroy.
		allowed_tags = ["minecraft:sand", "minecraft:dirt", "forge:stone", "forge:cobblestone", "forge:sandstone", "minecraft:logs", "minecraft:planks"]
		#The strength of the explosion curse event's explosion.
		strength = 4.0

	[curses.teleport_randomly]
		#The chance of the teleport_randomly event being triggered. Set to 0 to disable.
		chance = 0.05000000074505806
		#The badness of the teleport_randomly curse event. Determines what doll tiers can cause it.
		#Allowed Values: BAD, WORSE, WORST
		badness = "WORST"
		#The distance of the teleport_randomly curse event's teleportation.
		distance = 1000

	[curses.swap_hands]
		#The chance of the swap_hands event being triggered. Set to 0 to disable.
		chance = 0.25
		#The badness of the swap_hands curse event. Determines what doll tiers can cause it.
		#Allowed Values: BAD, WORSE, WORST
		badness = "BAD"

	[curses.blindness]
		#The chance of the blindness event being triggered. Set to 0 to disable.
		chance = 0.05000000074505806
		#The badness of the blindness curse event. Determines what doll tiers can cause it.
		#Allowed Values: BAD, WORSE, WORST
		badness = "BAD"
		#The minimum amount of minutes that the blindness event lasts for.
		minimum_minutes = 1.0
		#The maximum amount of minutes that the blindness event lasts for.
		maximum_minutes = 3.0

	[curses.top_down_camera]
		#The chance of the top_down_camera event being triggered. Set to 0 to disable.
		chance = 0.05000000074505806
		#The badness of the top_down_camera curse event. Determines what doll tiers can cause it.
		#Allowed Values: BAD, WORSE, WORST
		badness = "WORSE"
		#The minimum amount of minutes that the top_down_camera event lasts for.
		minimum_minutes = 1.0
		#The maximum amount of minutes that the top_down_camera event lasts for.
		maximum_minutes = 5.0

	[curses.teleport_to_cave]
		#The chance of the teleport_to_cave event being triggered. Set to 0 to disable.
		chance = 0.05000000074505806
		#The badness of the teleport_to_cave curse event. Determines what doll tiers can cause it.
		#Allowed Values: BAD, WORSE, WORST
		badness = "WORSE"
		#The radius of the teleport_to_cave event's teleportation area. This only applies to horizontal coordinates.
		range = 16

	[curses.zombie_horde]
		#The chance of the zombie_horde event being triggered. Set to 0 to disable.
		chance = 0.05000000074505806
		#The badness of the zombie_horde curse event. Determines what doll tiers can cause it.
		#Allowed Values: BAD, WORSE, WORST
		badness = "WORSE"
		#The vertical radius of the zombie_horde event's spawn area.
		vertical_range = 10
		#The horizontal radius of the zombie_horde event's spawn area.
		horizontal_range = 32
		#The average amount of zombies that the zombie_horde should spawn.
		amount = 15

	[curses.reverse_controls]
		#The chance of the reverse_controls event being triggered. Set to 0 to disable.
		chance = 0.10000000149011612
		#The badness of the reverse_controls curse event. Determines what doll tiers can cause it.
		#Allowed Values: BAD, WORSE, WORST
		badness = "WORSE"
		#The minimum amount of minutes that the reverse_controls event lasts for.
		minimum_minutes = 0.5
		#The maximum amount of minutes that the reverse_controls event lasts for.
		maximum_minutes = 2.0

	[curses.shuffle_inventory]
		#The chance of the shuffle_inventory event being triggered. Set to 0 to disable.
		chance = 0.10000000149011612
		#The badness of the shuffle_inventory curse event. Determines what doll tiers can cause it.
		#Allowed Values: BAD, WORSE, WORST
		badness = "BAD"

