// Listen to item tag event
onEvent('tags.items', event => {
  // Create the #buddycards:epic tag collection and add specific buddycards to it
  event.add('buddycards:epic', [
    'buddycards:buddycard_base26',
    'buddycards:buddycard_base27',
    'buddycards:buddycard_nether26',
    'buddycards:buddycard_nether27',
    'buddycards:buddycard_end26',
    'buddycards:buddycard_end27',
    'buddycardsexp:buddycard_create26',
    'buddycardsexp:buddycard_create27',
    'buddycardsexp:buddycard_farmers17',
    'buddycardsexp:buddycard_farmers18'
    ])

    // Create the #buddycards:rare tag collection and add specific buddycards to it
  event.add('buddycards:rare', [
    'buddycards:buddycard_base22',
    'buddycards:buddycard_base23',
    'buddycards:buddycard_base24',
    'buddycards:buddycard_base25',
    'buddycards:buddycard_base35',
    'buddycards:buddycard_base36',
    'buddycards:buddycard_nether22',
    'buddycards:buddycard_nether23',
    'buddycards:buddycard_nether24',
    'buddycards:buddycard_nether25',
    'buddycards:buddycard_end22',
    'buddycards:buddycard_end23',
    'buddycards:buddycard_end24',
    'buddycards:buddycard_end25',
    'buddycardsexp:buddycard_create22',
    'buddycardsexp:buddycard_create23',
    'buddycardsexp:buddycard_create24',
    'buddycardsexp:buddycard_create25',
    'buddycardsexp:buddycard_farmers14',
    'buddycardsexp:buddycard_farmers15',
    'buddycardsexp:buddycard_farmers16'
    ])

      // Create the #buddycards:uncommon tag collection and add specific buddycards to it
  event.add('buddycards:uncommon', [
    'buddycards:buddycard_base13',
    'buddycards:buddycard_base14',
    'buddycards:buddycard_base15',
    'buddycards:buddycard_base16',
    'buddycards:buddycard_base17',
    'buddycards:buddycard_base18',
    'buddycards:buddycard_base19',
    'buddycards:buddycard_base20',
    'buddycards:buddycard_base21',
    'buddycards:buddycard_base32',
    'buddycards:buddycard_base33',
    'buddycards:buddycard_base34',
    'buddycards:buddycard_nether13',
    'buddycards:buddycard_nether14',
    'buddycards:buddycard_nether15',
    'buddycards:buddycard_nether16',
    'buddycards:buddycard_nether17',
    'buddycards:buddycard_nether18',
    'buddycards:buddycard_nether19',
    'buddycards:buddycard_nether20',
    'buddycards:buddycard_nether21',
    'buddycards:buddycard_end13',
    'buddycards:buddycard_end14',
    'buddycards:buddycard_end15',
    'buddycards:buddycard_end16',
    'buddycards:buddycard_end17',
    'buddycards:buddycard_end18',
    'buddycards:buddycard_end19',
    'buddycards:buddycard_end20',
    'buddycards:buddycard_end21',
    'buddycardsexp:buddycard_create13',
    'buddycardsexp:buddycard_create14',
    'buddycardsexp:buddycard_create15',
    'buddycardsexp:buddycard_create16',
    'buddycardsexp:buddycard_create17',
    'buddycardsexp:buddycard_create18',
    'buddycardsexp:buddycard_create19',
    'buddycardsexp:buddycard_create20',
    'buddycardsexp:buddycard_create21',
    'buddycardsexp:buddycard_farmers8',
    'buddycardsexp:buddycard_farmers9',
    'buddycardsexp:buddycard_farmers10',
    'buddycardsexp:buddycard_farmers11',
    'buddycardsexp:buddycard_farmers12',
    'buddycardsexp:buddycard_farmers13'
    ])

        // Create the #buddycards:common tag collection and add specific buddycards to it
  event.add('buddycards:common', [
    'buddycards:buddycard_base1',
    'buddycards:buddycard_base2',
    'buddycards:buddycard_base3',
    'buddycards:buddycard_base4',
    'buddycards:buddycard_base5',
    'buddycards:buddycard_base6',
    'buddycards:buddycard_base7',
    'buddycards:buddycard_base8',
    'buddycards:buddycard_base9',
    'buddycards:buddycard_base10',
    'buddycards:buddycard_base11',
    'buddycards:buddycard_base12',
    'buddycards:buddycard_base28',
    'buddycards:buddycard_base29',
    'buddycards:buddycard_base30',
    'buddycards:buddycard_base31',
    'buddycards:buddycard_nether1',
    'buddycards:buddycard_nether2',
    'buddycards:buddycard_nether3',
    'buddycards:buddycard_nether4',
    'buddycards:buddycard_nether5',
    'buddycards:buddycard_nether6',
    'buddycards:buddycard_nether7',
    'buddycards:buddycard_nether8',
    'buddycards:buddycard_nether9',
    'buddycards:buddycard_nether10',
    'buddycards:buddycard_nether11',
    'buddycards:buddycard_nether12',
    'buddycards:buddycard_end1',
    'buddycards:buddycard_end2',
    'buddycards:buddycard_end3',
    'buddycards:buddycard_end4',
    'buddycards:buddycard_end5',
    'buddycards:buddycard_end6',
    'buddycards:buddycard_end7',
    'buddycards:buddycard_end8',
    'buddycards:buddycard_end9',
    'buddycards:buddycard_end10',
    'buddycards:buddycard_end11',
    'buddycards:buddycard_end12',
    'buddycardsexp:buddycard_create1',
    'buddycardsexp:buddycard_create2',
    'buddycardsexp:buddycard_create3',
    'buddycardsexp:buddycard_create4',
    'buddycardsexp:buddycard_create5',
    'buddycardsexp:buddycard_create6',
    'buddycardsexp:buddycard_create7',
    'buddycardsexp:buddycard_create8',
    'buddycardsexp:buddycard_create9',
    'buddycardsexp:buddycard_create10',
    'buddycardsexp:buddycard_create11',
    'buddycardsexp:buddycard_create12',
    'buddycardsexp:buddycard_farmers1',
    'buddycardsexp:buddycard_farmers2',
    'buddycardsexp:buddycard_farmers3',
    'buddycardsexp:buddycard_farmers4',
    'buddycardsexp:buddycard_farmers5',
    'buddycardsexp:buddycard_farmers6',
    'buddycardsexp:buddycard_farmers7'
    ])



  })

